import 'materialize-css/dist/js/materialize.min'
import 'materialize-css/dist/css/materialize.min.css'
import './static/css/style.scss'
import './static/js/map.js'
import './static/js/slider.js'
import './static/js/toolbar.js'
